 spring:  
      application:  
        name: rabbitmq-hello  
      rabbitmq:  
        host: 192.168.9.42  
        port: 5672  
        username: hiya_rabbit  
        password: hiya_rabbit  